In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import importlib
import gc
import io
import os

from config import ROOT, paths  # lib này được khởi tạo ban đầu dự án

from IPython.display import display

pd.set_option('display.max_columns', 99)
pd.set_option('display.max_rows', 200)

pd.reset_option('display.float_format')
pd.set_option('display.max_colwidth', None)


import helpers.view as view
import helpers.EDA as EDA
import modules.utils as utils
from config import app_categorical_features

importlib.reload(view)
importlib.reload(EDA)
importlib.reload(utils)

from helpers.cache_clear import cache_clear
for name, path in paths.items():
    if os.path.isfile(path):
        print(f"{name}: tồn tại")
    else:
        print(f"{name}: không tồn tại")

train: tồn tại
test: tồn tại
prev: tồn tại
installments: tồn tại
credit_card: tồn tại
pos_cash: tồn tại
bureau: tồn tại
bureau_balance: tồn tại
description: tồn tại

In [2]:
lgbm_imp = pd.read_csv(ROOT + "/.log/_used/lgbm_imp_high_var_f1.csv")

In [5]:
lgbm_imp["feature"].nunique()

55801

In [2]:
def read(filename):
    try:
        with open(filename, 'r') as f:
            features = [line.strip() for line in f]
        return features
    except FileNotFoundError:
        print(f"Lỗi: Không tìm thấy file {filename}")
        return None
    except Exception as e:
        print(f"Lỗi khi đọc file {filename}: {e}")
        return None

In [ ]:
from rapidfuzz import fuzz

def find_fuzzy_matches(list1, list2, threshold=96):
    matches = []
    for a in list1:
        for b in list2:
            score = fuzz.ratio(a, b)
            if threshold <= score <= 100:
                matches.append((a, b, score))
    # Sắp xếp theo score giảm dần
    matches.sort(key=lambda x: x[2], reverse=True)
    return matches

def find_common_elements(list1, list2):
    return list(set(list1) & set(list2))

lb = pd.read_csv(ROOT + "/data/lb804.csv")["feature"].str.replace(r'[+()\-,. ]', '_', regex=True).replace(r'[_m_]', '_s_').to_list()
li = pd.Series(lgbm_imp_sorted_2["feature"].unique()).str.replace(r'[+()\-,. ]', '_', regex=True).tolist()

res=find_fuzzy_matches(lb, li)
print(*res, len(res),sep="\n")

In [4]:
lb = pd.read_csv(ROOT + "/data/lb804.csv")["feature"].str.replace(r'[/\- ]', '_', regex=True).to_list()

In [13]:
li = read(ROOT + "/data/result/low_corr_target.txt")

In [14]:
res=find_common_elements(lb, li)
print(*res, len(res),sep="\n")

f002_OCCUPATION_TYPE
f002_WEEKDAY_APPR_PROCESS_START
f101_approved_DAYS_LAST_DUE_d_app_DAYS_REGISTRATION_min
f001_YEARS_BEGINEXPLUATATION_MODE
f001_YEARS_BEGINEXPLUATATION_MEDI
f101_approved_DAYS_LAST_DUE_d_app_DAYS_BIRTH_mean
f001_alldocs_mean
f101_approved_DAYS_FIRST_DUE_d_app_DAYS_LAST_PHONE_CHANGE_mean
f101_approved_DAYS_LAST_DUE_d_app_DAYS_ID_PUBLISH_min
f001_AMT_REQ_CREDIT_BUREAU_QRT
f101_approved_DAYS_TERMINATION_d_app_DAYS_ID_PUBLISH_min
f101_approved_DAYS_FIRST_DUE_d_app_DAYS_ID_PUBLISH_min
f101_approved_DAYS_FIRST_DUE_d_app_DAYS_LAST_PHONE_CHANGE_min
f101_nyg_low_normal_DAYS_LAST_DUE_d_app_DAYS_REGISTRATION_min
f101_nyg_high_amt_paid_sum
f101_nyg_low_normal_AMT_ANNUITY_d_app_AMT_ANNUITY_min
f101_approved_NAME_TYPE_SUITE_Unaccompanied_mean
f101_approved_DAYS_TERMINATION_d_app_DAYS_BIRTH_min
f002_NAME_FAMILY_STATUS
f101_completed_AMT_GOODS_PRICE_d_AMT_CREDIT_min
f101_completed_DAYS_FIRST_DUE_d_app_DAYS_BIRTH_mean
f101_approved_DAYS_TERMINATION_d_app_DAYS_REGISTRATION_min
f101_approved_DAYS_TERMINATION_d_app_DAYS_LAST_PHONE_CHANGE_min
f101_completed_WEEKDAY_APPR_PROCESS_START_FRIDAY_mean
f101_nyg_middle_AMT_ANNUITY_d_app_AMT_ANNUITY_max
f001_building_score_mode_std
26

In [3]:
used_f0_f101 = pd.read_csv(ROOT + "/.log/_used/5_lightgbm_4_used_2_f0_f101.csv")
used_f0_f102 = pd.read_csv(ROOT + "/.log/_used/5_lightgbm_4_used_2_f0_f102.csv")
used_f0_f103 = pd.read_csv(ROOT + "/.log/_used/5_lightgbm_4_used_2_f0_f103.csv")
used_f0_f104 = pd.read_csv(ROOT + "/.log/_used/5_lightgbm_4_used_2_f0_f104.csv")
used_f0_f105_ = pd.read_csv(ROOT + "/.log/_used/5_lightgbm_4_used_2_f0_f105_f106_f107_f108.csv")
used_f0_f101["data"] = 1
used_f0_f102["data"] = 2
used_f0_f103["data"] = 3
used_f0_f104["data"] = 4
used_f0_f105_["data"] = 5
used = pd.concat([used_f0_f101, used_f0_f102, used_f0_f103, used_f0_f104, used_f0_f105_])

low_corr_f0_f101 = pd.read_csv(ROOT + "/.log/_used/6_lightgbm_2_low_corr_target_f0_f101.csv")
low_corr_f0_f102 = pd.read_csv(ROOT + "/.log/_used/6_lightgbm_2_low_corr_target_f0_f102.csv")
low_corr_f0_f103 = pd.read_csv(ROOT + "/.log/_used/6_lightgbm_2_low_corr_target_f0_f103.csv")
low_corr_f0_f104 = pd.read_csv(ROOT + "/.log/_used/6_lightgbm_2_low_corr_target_f0_f104.csv")
low_corr_f0_f105_ = pd.read_csv(ROOT + "/.log/_used/6_lightgbm_2_low_corr_target_f0_f105_f106_f107_f108.csv")
low_corr_f0_f101["data"] = 1
low_corr_f0_f102["data"] = 2
low_corr_f0_f103["data"] = 3
low_corr_f0_f104["data"] = 4
low_corr_f0_f105_["data"] = 5
low_corr = pd.concat([low_corr_f0_f101, low_corr_f0_f102, low_corr_f0_f103, low_corr_f0_f104, low_corr_f0_f105_])

In [7]:
used

,chunk,feature,importance_gain,importance_split,data
0,1,f001_AMT_GOODS_PRICE-d-AMT_CREDIT,10245.974209,391,1
1,1,f001_AMT_CREDIT-d-CNT_CHILDREN,2132.418046,181,1
2,1,f001_AMT_CREDIT-d-CNT_FAM_MEMBERS,3411.716046,268,1
3,1,f001_AMT_CREDIT,1499.469953,98,1
4,1,f001_AMT_GOODS_PRICE-d-CNT_FAM_MEMBERS,2835.283613,214,1
...,...,...,...,...,...
881,2,f108_past_payment_72m,0.000000,0,5
882,2,f108_past_payment_6m,3877.606699,333,5
883,2,f108_past_payment_7m,3519.769511,309,5
884,2,f108_past_payment_9m,3859.589447,339,5
885,2,f108_past_payment_8m,3925.275669,334,5

In [8]:
used["feature"].nunique()

21359

In [65]:
lightgbm_low_imp_used = pd.read_csv(ROOT + "/.log/_used/7_lightgbm_filtered_low_imp_used.csv").sort_values(["chunk", "importance_gain", "auc_valid", "auc_train"], ascending=[True, False, False, False])
lightgbm_low_imp_low_corr = pd.read_csv(ROOT + "/.log/_used/7_lightgbm_filtered_low_imp_low_corr.csv").sort_values(["chunk", "importance_gain", "auc_valid", "auc_train"], ascending=[True, False, False, False])
lightgbm_hight_imp_used = pd.read_csv(ROOT + "/.log/_used/7_lightgbm_filtered_high_imp_used.csv").sort_values(["chunk", "importance_gain", "auc_valid", "auc_train"], ascending=[True, False, False, False])
lightgbm_hight_imp_low_corr = pd.read_csv(ROOT + "/.log/_used/7_lightgbm_filtered_high_imp_low_corr.csv").sort_values(["chunk", "importance_gain", "auc_valid", "auc_train"], ascending=[True, False, False, False])

In [68]:
def filter_by_threshold(chunk_data, per=80):
    a = chunk_data.shape
    threshold_gain = min(np.percentile(chunk_data["importance_gain"], per), 1000)
    threshold_auc_valid = min(np.percentile(chunk_data["auc_valid"], per), 0.6)
    threshold_split = min(np.percentile(chunk_data["importance_split"], per), 2)
    res = chunk_data[(chunk_data["importance_gain"] > threshold_gain) & (chunk_data["auc_valid"] > threshold_auc_valid) & (chunk_data["importance_split"] > threshold_split)]
    b = res.shape
    print(f"{a} => {b}")
    return res # lấy threshold là phân vị default 80%

# lấy phân vị cao hơn cho low importance

In [69]:
lightgbm_low_imp_used = filter_by_threshold(lightgbm_low_imp_used, per=95)

(15808, 6) => (535, 6)

In [70]:
lightgbm_low_imp_low_corr = filter_by_threshold(lightgbm_low_imp_low_corr, per=95)

(15808, 6) => (566, 6)

# lấy phân vị thấp hơn cho high importance

In [71]:
lightgbm_hight_imp_used = filter_by_threshold(lightgbm_hight_imp_used, per=85)

(5975, 6) => (865, 6)

In [72]:
lightgbm_hight_imp_low_corr = filter_by_threshold(lightgbm_hight_imp_low_corr, per=80)

(5975, 6) => (1173, 6)

In [73]:
lightgbm_low_imp_used["_data"] = "low_imp_high_corr"
lightgbm_low_imp_low_corr["_data"] = "low_imp_low_corr"
lightgbm_hight_imp_used["_data"] = "high_imp_high_corr"
lightgbm_hight_imp_low_corr["_data"] = "high_imp_low_corr"

C:\Users\Admin\AppData\Local\Temp\ipykernel_23296\4160023060.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lightgbm_low_imp_used["_data"] = "low_imp_high_corr"

In [82]:
used = pd.concat([lightgbm_low_imp_used, lightgbm_low_imp_low_corr, lightgbm_hight_imp_used, lightgbm_hight_imp_low_corr]).reset_index( drop=True).drop_duplicates(keep="first")

In [83]:
used

,chunk,feature,importance_gain,importance_split,auc_train,auc_valid,_data
0,1,f101_approved_DAYS_DECISION_s_app_DAYS_BIRTH_min,21110.819803,580,0.782416,0.694288,low_imp_high_corr
1,1,f002_NAME_EDUCATION_TYPE,15699.589653,221,0.782416,0.694288,low_imp_high_corr
2,1,f101_approved_DAYS_DECISION_s_app_DAYS_EMPLOYED_min,15219.129778,681,0.782416,0.694288,low_imp_high_corr
3,1,f001_REGION_RATING_CLIENT,11986.649599,384,0.782416,0.694288,low_imp_high_corr
4,1,f101_completed_AMT_GOODS_PRICE_s_app_AMT_ANNUITY_d_app_AMT_INCOME_TOTAL_max,11949.453747,573,0.782416,0.694288,low_imp_high_corr
...,...,...,...,...,...,...,...
3134,10,f105_past_payment_18m_min,616.188871,49,0.836925,0.767994,high_imp_low_corr
3135,10,f108_past_payment_5m,610.590638,54,0.836925,0.767994,high_imp_low_corr
3136,10,f105_past_payment_7m_max,608.722232,53,0.836925,0.767994,high_imp_low_corr
3137,10,f108_DAYS_TERMINATION-s-app_DAYS_ID_PUBLISH,606.391180,55,0.836925,0.767994,high_imp_low_corr
3138,10,f108_past_payment_9m,602.607031,52,0.836925,0.767994,high_imp_low_corr

In [80]:
used["feature"].nunique()

1476

In [ ]:
trte[trte["data"] == 1].to_pickle(ROOT + "/data/processed/f0012_train.p")

In [ ]:
# from config import reload_config
# reload_config()

from config import reload
reload()
from config import use_cols

In [ ]:
import numpy as np
import cupy as cp
import time

# cpu
x_cpu = np.random.rand(10000, 10000).astype(np.float32)
start = time.time()
result_cpu = x_cpu @ x_cpu
print("CPU time:", time.time() - start)

# gpu
x_gpu = cp.random.rand(10000, 10000, dtype=cp.float32)
start = time.time()
result_gpu = x_gpu @ x_gpu
cp.cuda.Device(0).synchronize()  # bất đồng bộ gpu
print("GPU time:", time.time() - start)

CPU time: 6.711676597595215
GPU time: 1.1169979572296143